In [21]:
import csv
f= csv.open("guns.csv",'r')
data = list(csv.reader(f))
for i in range(5):
    print(data[i])

AttributeError: 'module' object has no attribute 'open'

In [22]:
import csv
f= open("guns.csv",'r')
data = list(csv.reader(f))
for i in range(5):
    print(data[i])

['', 'year', 'month', 'intent', 'police', 'sex', 'age', 'race', 'hispanic', 'place', 'education']
['1', '2012', '01', 'Suicide', '0', 'M', '34', 'Asian/Pacific Islander', '100', 'Home', '4']
['2', '2012', '01', 'Suicide', '0', 'F', '21', 'White', '100', 'Street', '3']
['3', '2012', '01', 'Suicide', '0', 'M', '60', 'White', '100', 'Other specified', '4']
['4', '2012', '02', 'Suicide', '0', 'M', '64', 'White', '100', 'Home', '4']


In [23]:
headers = data[0]
data = data[1:]
print(headers)
for i in range(5):
    print(data[i])

['', 'year', 'month', 'intent', 'police', 'sex', 'age', 'race', 'hispanic', 'place', 'education']
['1', '2012', '01', 'Suicide', '0', 'M', '34', 'Asian/Pacific Islander', '100', 'Home', '4']
['2', '2012', '01', 'Suicide', '0', 'F', '21', 'White', '100', 'Street', '3']
['3', '2012', '01', 'Suicide', '0', 'M', '60', 'White', '100', 'Other specified', '4']
['4', '2012', '02', 'Suicide', '0', 'M', '64', 'White', '100', 'Home', '4']
['5', '2012', '02', 'Suicide', '0', 'M', '31', 'White', '100', 'Other specified', '2']


In [24]:
year_counts={}
for r in data:
    if(r[1] not in year_counts):
        year_counts[r[1]]=1
    else:
        year_counts[r[1]]=year_counts[r[1]]+1
print(year_counts)

{'2012': 33563, '2013': 33636, '2014': 33599}


In [25]:
import datetime
dates = []
dates = [datetime.datetime(year=int(r[1]),month=int(r[2]),day=1)for r in data]
for d in range(5):
    print(dates[d])
print(type(dates[0]))

2012-01-01 00:00:00
2012-01-01 00:00:00
2012-01-01 00:00:00
2012-02-01 00:00:00
2012-02-01 00:00:00
<class 'datetime.datetime'>


In [26]:
#date_counts = {1 if( str(d) not in date_counts) else (date_counts[str(d)]+1) for d in dates}
date_counts = {}
for d in dates:
    if str(d) not in date_counts:
        date_counts[str(d)]=1
    else:
        date_counts[str(d)]+=1
print(date_counts)


{'2012-03-01 00:00:00': 2743, '2014-08-01 00:00:00': 2970, '2012-11-01 00:00:00': 2729, '2012-06-01 00:00:00': 2826, '2012-07-01 00:00:00': 3026, '2013-02-01 00:00:00': 2375, '2012-10-01 00:00:00': 2733, '2014-02-01 00:00:00': 2361, '2013-10-01 00:00:00': 2808, '2013-06-01 00:00:00': 2920, '2014-09-01 00:00:00': 2914, '2013-04-01 00:00:00': 2798, '2014-05-01 00:00:00': 2864, '2013-01-01 00:00:00': 2864, '2012-02-01 00:00:00': 2357, '2014-11-01 00:00:00': 2756, '2014-07-01 00:00:00': 2884, '2012-09-01 00:00:00': 2852, '2013-07-01 00:00:00': 3079, '2013-09-01 00:00:00': 2742, '2014-12-01 00:00:00': 2857, '2012-01-01 00:00:00': 2758, '2013-08-01 00:00:00': 2859, '2014-01-01 00:00:00': 2651, '2012-04-01 00:00:00': 2795, '2013-05-01 00:00:00': 2806, '2014-06-01 00:00:00': 2931, '2013-03-01 00:00:00': 2862, '2013-11-01 00:00:00': 2758, '2012-08-01 00:00:00': 2954, '2013-12-01 00:00:00': 2765, '2014-03-01 00:00:00': 2684, '2014-04-01 00:00:00': 2862, '2012-05-01 00:00:00': 2999, '2012-12-01 0

In [27]:
sex_counts  = {}
for d in data:
    if(str(d[5]) not in sex_counts):
        sex_counts[str(d[5])]=1
    else:
        sex_counts[str(d[5])]+=1
print(sex_counts)

{'M': 86349, 'F': 14449}


In [28]:
race_counts  = {}
for d in data:
    if(str(d[7]) not in race_counts):
        race_counts[str(d[7])]=1
    else:
        race_counts[str(d[7])]+=1
print(race_counts)

{'Black': 23296, 'Asian/Pacific Islander': 1326, 'Hispanic': 9022, 'White': 66237, 'Native American/Native Alaskan': 917}


In [29]:
import csv
f = open("census.csv",'r')
census = list(csv.reader(f))

In [ ]:
print(census)

In [32]:
mapping = {}
mapping["Asian/Pacific Islander"]=int(census[1][14])+int(census[1][15])

In [33]:
mapping["Black"]=int(census[1][12])
mapping["Hispanic"]=int(census[1][11])
mapping["Native American/Native Alaskan"]=int(census[1][13])
mapping["White"]=int(census[1][10])


In [34]:
race_per_hundredk = {}
for c in race_counts:
    race_per_hundredk[c] = (race_counts[c]/mapping[c])*100000
#print(race_counts)
print(race_per_hundredk)

{'Black': 57.8773477735196, 'Asian/Pacific Islander': 8.374309664161762, 'Hispanic': 20.220491210910907, 'White': 33.56849303419181, 'Native American/Native Alaskan': 24.521955573811088}


In [43]:
intents  = []
races = []
homicide_race_counts={}
for d in data:
    intents.append(d[3])
    races.append(d[7])
for i,intent in enumerate(intents):
    if(intent=="Homicide"):
        if(races[i] not in homicide_race_counts):
            homicide_race_counts[races[i]]=1
        else:
            homicide_race_counts[races[i]]+=1
race_per_hundredk = {}
for c in race_counts:
    race_per_hundredk[c] = (race_counts[c]/mapping[c])*100000
print(homicide_race_counts)
#print(race_per_hundredk)

{'Black': 19510, 'Asian/Pacific Islander': 559, 'Hispanic': 5634, 'White': 9147, 'Native American/Native Alaskan': 326}


{'Black': 19510, 'Asian/Pacific Islander': 559, 'Hispanic': 5634, 'White': 9147, 'Native American/Native Alaskan': 326}